// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel BufferToTexture

// Create a RenderTexture with enableRandomWrite flag and set it
// with cs.SetTexture
RWTexture2D<float4> Result;
RWBuffer<int> Alive;
int Width;

[numthreads(8,8,1)]
void BufferToTexture (uint3 id : SV_DispatchThreadID)
{
    if (Alive[id.y * Width + id.x] == 1) {
        Result[id.xy] = float4(0, 1, 0, 1);
    } else {
        Result[id.xy] = float4(0, 0, 0, 1);
    }
}
